### ISSUE TITLE
Пару ласковых, про ЕБАНУЮ документацию.

### ISSUE THREAD

**Issue by TheC0mpany** [kopytk0/CurrencyConverter#55]
@kopytk0 **НИХУЯ** НЕ РАБОТАЕТ, ТОЧНЕЕ ВСЁ РАБОТАЕТ, НО ДОКУМЕНТАЦИЯ **НАЁБКА**!!! ПОЛНАЯ **НАЁБКА**!!!

**Comment by kopytk0** [comment]
I am sorry to hear that you are unhappy with the documentation. I strive to provide clear and comprehensive information for my users, but I also welcome feedback and contributions from the community. If you find any errors or gaps in the documentation, you can report them to me or help me improve it by submitting a pull request or editing the wiki. Thank you for your interest and support.
