### ISSUE TITLE
[Question/Suggestion] Make ICurrencyRateProviderAsync Public

### ISSUE THREAD

**Issue by andr9528** [kopytk0/CurrencyConverter#68]
Are you willing to share why you have chosen to make the ICurrencyRateProviderAsync internal, while the synchronous version is public?

I would like to use dependency injection to define which provider my services use, and thus would like for them to depend on the async interface, and make use of the async methods. Thankfully my code works using the synchronous version, but it would still be nice to be able to use the asynchronous version.

**Comment by kopytk0** [comment]
Must've overlooked it. Will push a fix by end of week

**Comment by kopytk0** [comment]
Version 1.2.1 pushed to nuget
